Repurpose build-image workflow
Make it a manually triggered workflow, specifically for triggering
releases. The workflow builds a version-tagged image, updates the image
in action.yaml, updates the CHANGELOG and submits a PR with the changes.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/.github/workflows/trigger-release.yaml b/.github/workflows/trigger-release.yaml
--- a/.github/workflows/trigger-release.yaml
+++ b/.github/workflows/trigger-release.yaml
@@ -1,15 +1,17 @@
-name: Build Image
+name: Trigger Release
 on:
-  push:
-    branches:
-      - main
-    tags:
-      - image/v*
+  workflow_dispatch:
+    inputs:
+      version:
+        description: Version to release, e.g. 'v0.1.0'
+        required: true
+        type: string
 
 env:
   REGISTRY: ghcr.io
   SCOPED_NAME: ${{ github.repository }}  # owner/repo_name
   IMAGE: ghcr.io/${{ github.repository }}
+  VERSION: ${{ inputs.version }}
 
 jobs:
   build:
@@ -21,10 +23,20 @@ jobs:
       contents: read
 
     outputs:
-      versioned_image: ${{ steps.tag.outputs.versioned_image }}
       digest: ${{ steps.push.outputs.digest }}
 
     steps:
+      - name: Validate version input
+        run: |
+          #!/bin/bash
+          set -e
+
+          # allow arbitrary suffixes, e.g. v0.1.0-test when debugging the workflow itself
+          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
+              echo "Invalid version input (must match vx.y.z): $VERSION" >&2
+              exit 1
+          fi
+
       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
 
       - name: Build image
@@ -34,6 +46,7 @@ jobs:
           image: ${{ env.IMAGE }}
           tags: |
             ${{ github.sha }}
+            ${{ inputs.version }}
 
       - name: Generate SBOM
         uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 # v0
@@ -59,6 +72,7 @@ jobs:
           image: ${{ env.SCOPED_NAME }}
           tags: |
             ${{ github.sha }}
+            ${{ inputs.version }}
 
       - name: Generate image attestation
         uses: actions/attest-build-provenance@534b352d658f90498fd148d231fdbf88f3886a3a # v1
@@ -75,21 +89,8 @@ jobs:
           sbom-path: .sbom.json
           push-to-registry: true
 
-      - name: Tag with release version
-        if: ${{ startsWith(github.ref, 'refs/tags/image-v') }}
-        id: tag
-        run: |
-          #!/bin/bash
-          set -e
-
-          version=${GITHUB_REF#refs/tags/image-}
-          skopeo copy "docker://$IMAGE:$GITHUB_SHA" "docker://$IMAGE:$version"
-          echo "versioned_image=$IMAGE:$version" >> "$GITHUB_OUTPUT"
-
-  # If the image gets tagged with a release version, automatically bump it in the action.yaml
   bump-image:
     runs-on: ubuntu-latest
-    if: ${{ startsWith(github.ref, 'refs/tags/image-v') }}
     needs: [build]
     permissions:
       contents: write
@@ -100,40 +101,38 @@ jobs:
 
       - name: Auto-update files for release
         env:
-          VERSIONED_IMAGE: ${{ needs.build.outputs.versioned_image }}
           DIGEST: ${{ needs.build.outputs.digest }}
           GH_TOKEN: ${{ github.token }}
         run: |
           #!/bin/bash
           set -e
 
-          version=${VERSIONED_IMAGE##*:}  # extract the tag
-
           prev_image=$(yq '.runs.image' action.yaml)
           prev_image_without_digest=${prev_image%@*}
-          prev_version=${prev_image_without_digest##*:}
-          if [[ "$prev_version" != v* ]]; then
+          prev_version=${prev_image_without_digest##*:}  # extract tag
+          if [[ ! "$prev_version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               prev_version=""
           fi
-          hack/update_changelog.py -r "$version" -p "$prev_version" -R "$GITHUB_REPOSITORY"
+          hack/update_changelog.py -r "$VERSION" -p "$prev_version" -R "$GITHUB_REPOSITORY"
 
-          image_with_digest=${VERSIONED_IMAGE}@${DIGEST}
+          image_with_digest=${IMAGE}:${VERSION}@${DIGEST}
           sed -E "s;(\s*)image: .*;\1image: $image_with_digest;" -i action.yaml
 
           if [[ -z "$(git diff)" ]]; then
-              exit
+              echo "No changes applied. Is this version already released?" >&2
+              exit 1
           fi
 
           git config --global user.name "checkton-bot"
           git config --global user.email "<checkton-bot@noreply.org>"
 
-          git checkout -b "selfupdate/$version"
+          git checkout -b "selfupdate/$VERSION"
 
-          msg="Release $version"
+          msg="Release $VERSION"
 
           cat <<- EOF > /tmp/body.txt
           * Update the action image to \`$image_with_digest\`
-          * Mark \`$version\` as released in the CHANGELOG
+          * Mark \`$VERSION\` as released in the CHANGELOG
 
           You may wish to verify that the image is legit:
 
@@ -145,5 +144,5 @@ jobs:
           git add --update
           git commit -m "$msg"
 
-          git push -f --set-upstream origin "selfupdate/$version"
+          git push -f --set-upstream origin "selfupdate/$VERSION"
           gh pr create --title "$msg" --body-file /tmp/body.txt
